<?php
//$formData[funcionality] (1)

$dataExample[1]="INSERT INTO `cms_foodservice` (`id`, `resumen1`, `enlace_r1`, `imagen_r1`, `resumen2`, `enlace_r2`, `imagen_r2`, `resumen3`, `enlace_r3`, `imagen_r3`, `contenido`, `imagenInt1`, `imagenInt2`) VALUES
(1, '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sit amet auctor urna. Aenean adipiscing massa nec magna varius et ullamcorper metus posuere. Curabitur dapibus urna nec justo condimentum nec semper arcu dignissim. Maecenas id ante diam. Praesent libero velit, tempus a pulvinar non, blandit sed mi. Fusce varius pharetra varius. Suspendisse non dolor tellus, at venenatis velit.</p>', 'foodservice.php', 'imagen.jpg', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sit amet auctor urna. Aenean adipiscing massa nec magna varius et ullamcorper metus posuere. Curabitur dapibus urna nec justo condimentum nec semper arcu dignissim. Maecenas id ante diam. Praesent libero velit, tempus a pulvinar non, blandit sed mi. Fusce varius pharetra varius. Suspendisse non dolor tellus, at venenatis velit.</p>', 'foodservice.php', 'imagen.jpg',  '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sit amet auctor urna. Aenean adipiscing massa nec magna varius et ullamcorper metus posuere. Curabitur dapibus urna nec justo condimentum nec semper arcu dignissim. Maecenas id ante diam. Praesent libero velit, tempus a pulvinar non, blandit sed mi. Fusce varius pharetra varius. Suspendisse non dolor tellus, at venenatis velit.</p>', 'foodservice.php', 'imagen.jpg','<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sit amet auctor urna. Aenean adipiscing massa nec magna varius et ullamcorper metus posuere. Curabitur dapibus urna nec justo condimentum nec semper arcu dignissim. Maecenas id ante diam. Praesent libero velit, tempus a pulvinar non, blandit sed mi. Fusce varius pharetra varius. Suspendisse non dolor tellus, at venenatis velit.</p>\r\n\r\n<p>Ut mattis mollis est, vel sagittis tortor ultrices quis. Quisque tincidunt tempus purus, a pretium urna molestie nec. Quisque eu lacus mauris, sed faucibus tellus. Vivamus ut scelerisque dui. Mauris lectus sem, viverra a pulvinar iaculis, facilisis sit amet orci. Ut adipiscing, massa ac elementum aliquam, orci nulla placerat nunc, in tempor eros sem sit amet massa. Morbi eu elit a diam rhoncus ultricies sit amet ac mauris. Nulla eget tortor purus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque porttitor lobortis metus auctor viverra. Sed gravida ornare nulla pretium sagittis. Integer pretium lacinia nisl eu venenatis. Vivamus ornare blandit magna, non adipiscing nibh aliquam at. Vestibulum et metus leo, quis tincidunt felis. Praesent a quam ut lacus elementum mollis quis id nibh.</p>', 'imagen1.jpg', 'imagen2.jpg');
";



?>