/* Load this script using conditional IE comments if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'icomoon\'">' + entity + '</span>' + html;
	}
	var icons = {
			'icon-home' : '&#xe000;',
			'icon-close' : '&#xe001;',
			'icon-plus' : '&#xe002;',
			'icon-close-2' : '&#xe003;',
			'icon-list' : '&#xe004;',
			'icon-list-2' : '&#xe005;',
			'icon-calendar' : '&#xe006;',
			'icon-pencil' : '&#xe007;',
			'icon-search' : '&#xe008;',
			'icon-folder' : '&#xe009;',
			'icon-trashcan' : '&#xe00a;',
			'icon-blocked' : '&#xe00b;',
			'icon-switch' : '&#xe00c;',
			'icon-location' : '&#xe00d;',
			'icon-checkmark' : '&#xe00e;',
			'icon-list-3' : '&#xe00f;',
			'icon-grid' : '&#xe010;',
			'icon-munis' : '&#xe011;',
			'icon-arrow-right' : '&#xe012;',
			'icon-arrow-left' : '&#xe013;',
			'icon-arrow-down' : '&#xe014;',
			'icon-arrow-up' : '&#xe015;',
			'icon-file-add' : '&#xe016;',
			'icon-file-remove' : '&#xe017;',
			'icon-refresh' : '&#xe018;',
			'icon-comment' : '&#xe019;',
			'icon-clock' : '&#xe01a;',
			'icon-paperplane' : '&#xe01b;',
			'icon-pencil-2' : '&#xe01c;',
			'icon-phone' : '&#xe01d;',
			'icon-mobile' : '&#xe01e;',
			'icon-paperclip' : '&#xe01f;',
			'icon-user' : '&#xe020;',
			'icon-users' : '&#xe021;',
			'icon-user-add' : '&#xe022;',
			'icon-location-2' : '&#xe023;',
			'icon-flag' : '&#xe024;',
			'icon-house' : '&#xe025;',
			'icon-comment-2' : '&#xe026;',
			'icon-chat' : '&#xe027;',
			'icon-clock-2' : '&#xe028;',
			'icon-browser' : '&#xe029;',
			'icon-calendar-2' : '&#xe02a;',
			'icon-cup' : '&#xe02b;',
			'icon-code' : '&#xe02c;',
			'icon-credit-card' : '&#xe02d;',
			'icon-plus-2' : '&#xe02e;',
			'icon-minus' : '&#xe02f;',
			'icon-cross' : '&#xe030;',
			'icon-plus-3' : '&#xe031;',
			'icon-cross-2' : '&#xe032;',
			'icon-plus-4' : '&#xe033;',
			'icon-minus-2' : '&#xe034;',
			'icon-minus-3' : '&#xe035;',
			'icon-cross-3' : '&#xe036;',
			'icon-checkmark-2' : '&#xe037;',
			'icon-login' : '&#xe038;',
			'icon-logout' : '&#xe039;',
			'icon-lock-open' : '&#xe03a;',
			'icon-lock' : '&#xe03b;',
			'icon-list-4' : '&#xe03c;',
			'icon-add-to-list' : '&#xe03d;',
			'icon-text' : '&#xe03e;',
			'icon-pictures' : '&#xe03f;',
			'icon-record' : '&#xe040;',
			'icon-disk' : '&#xe041;',
			'icon-bookmarks' : '&#xe042;',
			'icon-bookmark' : '&#xe043;',
			'icon-stop' : '&#xe044;',
			'icon-pause' : '&#xe045;',
			'icon-play' : '&#xe046;',
			'icon-next' : '&#xe047;',
			'icon-previous' : '&#xe048;',
			'icon-first' : '&#xe049;',
			'icon-last' : '&#xe04a;',
			'icon-resize-enlarge' : '&#xe04b;',
			'icon-resize-shrink' : '&#xe04c;',
			'icon-arrow-down-2' : '&#xe04d;',
			'icon-arrow-left-2' : '&#xe04e;',
			'icon-arrow-right-2' : '&#xe04f;',
			'icon-arrow-up-2' : '&#xe050;',
			'icon-arrow-down-3' : '&#xe051;',
			'icon-arrow-left-3' : '&#xe052;',
			'icon-arrow-up-3' : '&#xe053;',
			'icon-arrow-right-3' : '&#xe054;',
			'icon-arrow-left-4' : '&#xe055;',
			'icon-arrow-down-4' : '&#xe056;',
			'icon-arrow-up-4' : '&#xe057;',
			'icon-arrow-right-4' : '&#xe058;',
			'icon-arrow-left-5' : '&#xe059;',
			'icon-arrow-down-5' : '&#xe05a;',
			'icon-arrow-up-5' : '&#xe05b;',
			'icon-untitled' : '&#xe05c;',
			'icon-home-2' : '&#xe05d;',
			'icon-office' : '&#xe05e;',
			'icon-film' : '&#xe05f;',
			'icon-camera' : '&#xe060;',
			'icon-images' : '&#xe061;',
			'icon-image' : '&#xe062;',
			'icon-image-2' : '&#xe063;',
			'icon-connection' : '&#xe064;',
			'icon-file' : '&#xe065;',
			'icon-file-2' : '&#xe066;',
			'icon-profile' : '&#xe067;',
			'icon-cart' : '&#xe068;',
			'icon-cart-2' : '&#xe069;',
			'icon-cart-3' : '&#xe06a;',
			'icon-qrcode' : '&#xe06b;',
			'icon-folder-open' : '&#xe06c;',
			'icon-folder-2' : '&#xe06d;',
			'icon-clock-3' : '&#xe06e;',
			'icon-clock-4' : '&#xe06f;',
			'icon-alarm' : '&#xe070;',
			'icon-alarm-2' : '&#xe071;',
			'icon-users-2' : '&#xe072;',
			'icon-user-2' : '&#xe073;',
			'icon-user-3' : '&#xe074;',
			'icon-bubbles' : '&#xe075;',
			'icon-bubbles-2' : '&#xe076;',
			'icon-bubble' : '&#xe077;',
			'icon-bubbles-3' : '&#xe078;',
			'icon-bubbles-4' : '&#xe079;',
			'icon-bubble-2' : '&#xe07a;',
			'icon-users-3' : '&#xe07b;',
			'icon-user-4' : '&#xe07c;',
			'icon-signup' : '&#xe07d;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/icon-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};