<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title></title>
        <base href="<?php echo base_url('assets/project_assets') . '/' ?>"></base>
        <link href="css/style.css" rel="stylesheet" type="text/css" media="screen" />
        <script type="text/javascript" src="js/jquery-1.7.1.min.js"></script>
        <script type="text/javascript" src="js/jquery.mousewheel.js"></script>
        <script type="text/javascript" src="js/jquery.jscrollpane.min.js"></script>
        <script type="text/javascript">
            $(function() {
                $('.scroll-pane').jScrollPane();
            })
        </script>
        <script type="text/javascript">

		  var _gaq = _gaq || [];
		  _gaq.push(['_setAccount', 'UA-34907944-1']);
		  _gaq.push(['_trackPageview']);
		
		  (function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		  })();
		
		</script>

    </head>

    <body>


        <div class="conTerminos">
            <div class="titTerminos">
                <span class="tInfoContacto">Términos y condiciones</span>
            </div>
            <div class="conTxTerminos">
                <div class="scroll-pane">
                	<p class="txTerminos"><span>Información Legal</span></p>
                  <p class="txTerminos">Ventrevista España, S.L. con domicilio en Barcelona, España, en la Calle Diputación 279, 1-7; provista de CIF: B-65411688 e inscrita en el RMB T.42148, F.115, H.B-401.824 (en adelante "Ventrevista") es la titular y propietaria del Sitio Web www.ventrevista.es  (en adelante "Sitio Web").</p>
                  <p class="txTerminos">Ventrevista se reserva la posibilidad de modificar sin previo aviso, el diseño, presentación y/o configuración de este Sitio Web, así como algunos o todos los servicios, y añadir servicios nuevos. Ventrevista entiende por CLIENTE, los usuarios personas jurídicas que contratan el servicio de Ventrevista para procesos de selección de personal. Ventrevista entiende como CANDIDATO a las personas físicas que graben a una vídeo entrevista previamente invitado por un CLIENTE a través de la plataforma de Ventrevista.</p>
                  <br>
                  <p class="txTerminos"><span>Términos y condiciones para CLIENTES (Personas Jurídicas)</span></p>
                  <br>
                  <p class="txTerminos"><span>Objeto</span></p>
                  <p class="txTerminos">Las presentes Condiciones Legales se aplican  a la prestación de servicios por parte de VENTREVISTA, al proporcionar una serie de paquetes de video-entrevistas a través de Internet para ser utilizadas por el CLIENTE en sus procesos de selección de personal, a cambio del pago de un precio. VENTREVISTA es la distribuidora oficial acreditada y exclusiva del software señalado anteriormente, cuya propiedad intelectual pertenece a Ventrevista S.A.</p>
                  <p class="txTerminos"><span>Disponibilidad temporal de los videos</span></p>
                  <p class="txTerminos">Las video-entrevistas que, formando un paquete, sean adquiridas por parte del CLIENTE, podrán ser consumidas dentro del año posterior a la fecha de adquisición, sirviendo como fecha de inicio la fecha de la factura.</p>
                  <p class="txTerminos">De todos modos, las entrevistas utilizadas por el cliente, quedarán grabadas y almacenadas en la base de datos y servidor propiedad de VENTREVISTA, con la finalidad de que el CLIENTE pueda acceder a las mismas para su consulta, con un número de veces ilimitado. El CLIENTE tendrá acceso a visualizar las video-entrevistas, realizadas por parte de sus candidatos, por un período máximo de un (1) año desde la grabación de las mismas.</p>
                  <p class="txTerminos"><span>Responsabilidades</span></p>
                  <p class="txTerminos">VENTREVISTA en ningún caso es responsable de las actividades que se realicen con motivo de la utilización de sus paquetes de video-entrevistas o de los servicios prestados, pero en todo caso se reserva el derecho a suspender o cancelar el contrato del CLIENTE en el caso de que tales paquetes se utilicen para realizar actividades ilegales. El CLIENTE certifica que, de acuerdo con su conocimiento, el uso de las video-entrevistas no afectan al honor, intimidad o propia imagen de terceros, ni se perjudica a personas ajenas.</p>
                  <p class="txTerminos">El CLIENTE es el único responsable del contenido de las video-entrevistas grabadas, y demás contenido de los productos o servicios contratados y en ningún caso incluirá contenidos contrarios a VENTREVISTA, a cualquier tercero, a las leyes, la moral o al orden publico. Del mismo modo, el CLIENTE acredita tener autorización para el alojamiento y tratamiento de los datos grabados, así como su correcta utilización, por parte de los usuarios de las entrevistas.</p>
                  <p class="txTerminos">Asimismo, el CLIENTE exonera a VENTREVISTA, de cualquier responsabilidad que pueda surgir con motivo del uso de los servicios contratados o de las relaciones del CLIENTE con terceros/usuarios. VENTREVISTA, podrá oponerse a la inclusión de contenidos interesados por el CLIENTE que sean contrarios a cualquier tercero, a las leyes, la moral o al orden publico.</p>
                  <p class="txTerminos"><span>Garantía de prestación de los servicios</span></p>
                  <p class="txTerminos">VENTREVISTA no puede garantizar que la disponibilidad de los servicios contratados sea continúa e ininterrumpida durante el período de vigencia del contrato, debido a la posibilidad de problemas en la red de Internet, averías en los equipos, servidores y otras posibles contingencias imprevisibles.</p>
                  <p class="txTerminos"><span>Acceso a los servicios por parte del cliente</span></p>
                  <p class="txTerminos">El acceso y uso de los servicios es responsabilidad exclusiva del CLIENTE, de tal manera que VENTREVISTA no se hace responsable de ninguna manera (ni directa ni subsidiariamente) de cualquier daño directo o indirecto, que el CLIENTE pueda ocasionar a terceros.</p>
                  <p class="txTerminos"><span>Mala fe en el uso de los servicios</span></p>
                  <p class="txTerminos">Se prohíbe el uso de los servicios contrarios a la buena fe y la realización de contenidos que resulten inadecuados para VENTREVISTA de conformidad con nuestra legislación, y en especial lo dispuesto en el artículo 8 de la LSSI y la recogida y/o utilización de datos personales de usuarios sin su consentimiento expreso o contraviniendo lo dispuesto en la Ley Orgánica 15/1999.</p>
                  <p class="txTerminos">El CLIENTE es el único responsable de la utilización y conservación del login (usuario) y contraseña habilitantes para el acceso a los servicios, que permiten contrastar a VENTREVISTA la autentificación del acceso y facilitar el permiso a las actuaciones que se soliciten desde las herramientas básicas de control de las video-entrevistas.</p>
                  <p class="txTerminos">El uso de estos identificadores y la comunicación, incluso a terceras personas, se produce bajo la única responsabilidad del CLIENTE.</p>
                  <p class="txTerminos">Propiedad del software</p>
                  <p class="txTerminos">El código empleado para la elaboración del software matriz de las video-entrevistas, el propio software utilizado en cada paquete, y las mismas video-entrevistas en cuanto aplicación informática, no son, en ningún caso, propiedad del cliente que no podrá utilizar su código con fines fraudulentos o sin la autorización de VENTREVISTA.</p>
                  <p class="txTerminos">El CLIENTE únicamente adquiere el derecho al uso del paquete de video-entrevistas contratado, en los términos señalados por VENTREVISTA y marcados en el Sitio Web</p>
                  <p class="txTerminos">El software matriz de los servicios prestados pertenece en exclusiva a VENTREVISTA S.A., siendo VENTREVISTA la autorizada oficial y exclusivamente para la prestación del servicio en territorio español. Dicha relación jurídica, se pone en conocimiento del CLIENTE, pero incumbe únicamente a aquellas partes.</p>
                  <p class="txTerminos"><span>Almacenamiento de datos en servidores de internet</span></p>
                  <p class="txTerminos">La recogida y tratamiento de los datos personales de los usuarios tiene como finalidad la prestación de los servicios que VENTREVISTA proporciona a través de su Sitio Web (consistente en la utilización de paquetes de video-entrevistas por parte del CLIENTE), así como el mantenimiento de la relación establecida, su gestión, administración, ampliación y mejora.</p>
                  <p class="txTerminos">De este modo, el CLIENTE presta expresamente su consentimiento para la cesión o comunicación, transferencia internacional y alojamiento tanto de sus datos, como los grabados en sus entrevistas, en los servidores contratados por parte de VENTREVISTA a una sociedad de hosting habilitada al efecto y dedicada a la prestación de servicios de alojamiento ubicada en Estados Unidos, entidad ésta dónde está alojado este Sitio Web, así como los datos personales y las video entrevistas objeto del servicio prestado a los usuarios.</p>
                  <p class="txTerminos">En este sentido, VENTREVISTA pone en conocimiento del usuario que sin la prestación del consentimiento para la citada transferencia internacional, no podrá perfeccionarse el contrato, ni por tanto, prestarse el servicio de video entrevista.</p>
                  <p class="txTerminos"><span>Protección de datos personales</span></p>
                  <p class="txTerminos">Mediante la contratación y aceptación de las condiciones del servicio prestado por VENTREVISTA, así como por la remisión de cualquier información a través de cualquier tipo de formularios electrónicos o por correo electrónico, fax, sms, etc. o mediante el simple uso de las video-entrevistas, el usuario manifiesta expresa e inequívocamente su consentimiento para que los datos de carácter personal suministrados, sean incorporados al fichero correspondiente y tratados con las finalidades indicadas.</p>
                  <p class="txTerminos">El CLIENTE se responsabilizará en todo caso de los datos grabados en sus entrevistas, y garantiza a VENTREVISTA que todos los usuarios de las mismas están informados acerca del tratamiento de sus datos personales.</p>
                  <p class="txTerminos">VENTREVISTA (en adelante, el ENCARGADO DEL TRATAMIENTO) asumirá las obligaciones legales que para el encargado del tratamiento de datos de carácter personal establecen la Ley Orgánica 15/1999, de 13 de Diciembre, de Protección de Datos de carácter personal, el Real Decreto 1720/2007 de 21 de Diciembre por el que se aprueba el Reglamento de desarrollo de la Ley Orgánica 15/1999, la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico y la Ley 1/1982 de 5 de mayo, de protección civil del honor, la intimidad y la propia imagen y demás legislación de desarrollo si, como consecuencia de la prestación de los servicios contratados, accediere a datos de carácter personal y, en particular, declara y garantiza al CLIENTE lo siguiente:</p>
                  <p class="txTerminos"><span>1)</span> Que, el ENCARGADO DEL TRATAMIENTO lo es a los efectos del artículo 12 de la LO 15/1.999 (LOPD) y se compromete a cumplir sus obligaciones como tal, no siendo por tanto el suministro de datos por parte del CLIENTE una cesión de datos a los efectos de la Ley.</p>
                  <p class="txTerminos"><span>2)</span> Que, los Servicios del ENCARGADO DEL TRATAMIENTO se prestarán de conformidad con los criterios, requisitos y especificaciones establecidos en las presente condiciones y en su defecto, por las instrucciones que en todo momento le de el CLIENTE.</p>
                  <p class="txTerminos"><span>3)</span> Que, Los destinatarios de la información son todos los departamentos en los que se organiza el RESPONSABLE y la finalidad de la recogida y el tratamiento es la gestión, archivo y mantenimiento de los datos personales de los clientes para una adecuada relación profesional con los mismos y para la facturación, contabilidad y cumplimiento de obligaciones fiscales derivadas, así como su control, desarrollo, ampliación y mejora.</p>
                  <p class="txTerminos"><span>4)</span> Que, el ENCARGADO DEL TRATAMIENTO se obliga a procesar los datos personales que le sean suministrados, únicamente para los fines para los que el CLIENTE se los facilite, es decir la prestación de los servicios objeto de las presentes condiciones.</p>
                  <p class="txTerminos">Podrán ser comunicados aquellos datos personales necesarios y no excesivos para el cumplimiento de las finalidades citadas de acuerdo con las cesiones previstas en la Ley Orgánica 15/1999, de 13 de diciembre, de Protección de Datos de Carácter Personal, entre otros, a los organismos y personas directamente relacionados con el responsables, a la Administración Tributaria y a bancos, cajas de ahorro y cajas rurales.</p>
                  <p class="txTerminos"><span>5)</span> Que, el ENCARGADO DEL TRATAMIENTO no comunicará los datos que le han sido suministrados a otras personas.</p>
                  <p class="txTerminos"><span>6)</span> Los datos personales facilitados por el CLIENTE, incluida su dirección de correo electrónico y todos aquellos a los cuales tenga acceso durante la relación establecida con usted, serán tratadas en un fichero titularidad del RESPONSABLE.</p>
                  <p class="txTerminos">El usuario presta expresamente y de manera inequívoca su consentimiento (Art. 6 de la LOPD) para que sus datos de carácter personal sean incorporados en el fichero del RESPONSABLE y tratados con estas finalidades.</p>
                  <p class="txTerminos">Los datos personales suministrados serán tratados con finalidades publicitarias y de prospección comercial para remitirle, por cualquier medio, incluido el correo postal o electrónico, SMS y cualquier otro medio equivalente, información de promociones, servicios y otros acontecimientos similares ofrecidos por VENTREVISTA o por terceros.</p>
                  <p class="txTerminos"><span>Medidas de protección de datos</span></p>
                  <p class="txTerminos">El ENCARGADO DEL TRATAMIENTO tomará todas las medidas razonables posibles para impedir la revelación, destrucción, alteración, divulgación o uso no autorizado de datos personales o el acceso físico o lógico no autorizado a los mismos. Las medidas abarcarán, a título enunciativo, hardware, software, procedimientos de recuperación, copias de seguridad y datos extraídos de datos personales en forma de exhibición en pantalla o impresa. Asimismo, el ENCARGADO DEL TRATAMIENTO observará en su tratamiento de los datos suministrados por el CLIENTE todas las medidas de seguridad, organizativas y técnicas, exigidas por el artículo 9 de la LOPD y de manera especial por el Real Decreto 1720/2007, por el que se aprueba el Reglamento de desarrollo de la Ley Orgánica 15/1999  como medidas de seguridad de nivel básico, así como las que la legislación vigente imponga en cada momento.  En caso de que sea necesario, el CLIENTE le indicará al ENCARGADO DEL TRATAMIENTO las medidas de nivel medio o alto que deba adoptar en el tratamiento, comprometiéndose éste a adoptarlas.</p>
                  <p class="txTerminos"><span>Prohibición de subcontratación en el tratamiento de datos</span></p>
                  <p class="txTerminos">Como regla general, el ENCARGADO DEL TRATAMIENTO no podrá subcontratar con un tercero la prestación de la totalidad o de parte de los servicios de Protección de Datos descritos en el presente acuerdo, salvo que medie previa autorización expresa del CLIENTE, la cual deberá ser informada con la debida antelación acerca de la entidad y de los servicios concretos a subcontratar. En este último supuesto, el ENCARGADO DEL TRATAMIENTO deberá formalizar un contrato con dicho tercero al amparo de lo dispuesto en el artículo 21 del citado Real Decreto 1720/2007.</p>
                  <p class="txTerminos">El ENCARGADO DEL TRATAMIENTO será responsable frente al CLIENTE, sin perjuicio de lo anterior, por los perjuicios causados como consecuencia del incumplimiento de las obligaciones contenidas en los artículos 9, 10 y 12 de la LOPD, y en el Real Decreto 1720/2007 en su integridad.</p>
                  <p class="txTerminos"><span>Cuestiones técnicas</span></p>
                  <p class="txTerminos">VENTREVISTA ofrecerá asistencia técnica referente al funcionamiento de los servicios/planes contratados por el CLIENTE en la forma que se indica a continuación:</p>
                  <p class="txTerminos"><span>-</span> Vía email a soporte@ventrevista.com, chat online y vía telefónica.</p>
                  <p class="txTerminos">No se ofrecerá soporte técnico en los siguientes casos:</p>
                  <p class="txTerminos"><span>-</span> Cuestiones referentes a configuración y utilización de servicios ofrecidos por terceros y ajenos a VENTREVISTA. Las cuestiones referentes a estos servicios deberán dirigirse al prestador del servicio en cuestión.</p>
                  <p class="txTerminos"><span>-</span> Cuestiones referentes a asistencia sobre modificación de software o código de programación, haya sido o no realizado por VENTREVISTA.</p>
                  <br>
                  <p class="txTerminos"><span>Términos y condiciones para CANDIDATOS (Personas Físicas)</span></p>
                  <br>
                  <p class="txTerminos">Antes de que usted acceda al sitio web (en adelante, la Aplicación ), haga uso, o utilice cualquiera de los servicios suministrados por Ventrevista S.A. , es importante que usted revise cuidadosamente los Términos generales del Servicio (en adelante, Términos ).</p>
                  <p class="txTerminos">Adicionalmente a los términos generales, algunas páginas específicas en la Aplicación pueden fijar términos y condiciones adicionales, los cuales están incorporados en los términos. Los Términos podrán ser modificados o actualizados en cualquier momento, pero usted puede encontrar siempre la versión más reciente aquí. En el caso de incongruencias entre los Términos Generales y la información incluida en otros lugares, siempre prevalecerá la información de los Términos.</p>
                  <p class="txTerminos">Al entrar y utilizar la Aplicación usted está aceptando los Términos y se limita a actuar de conformidad con lo allí estipulado. La aceptación de los Términos crea vínculo un legal entre usted y Ventrevista S.A.  y le obliga a utilizar el servicio únicamente en concordancia con los Términos.</p>
                  <p class="txTerminos">Si le surgieran dudas acerca de los Términos, puede usted contáctarnos en www.ventrevista.com.  El uso de la Aplicación y de sus diferentes servicios está condicionado por los Términos.</p>
                  <p class="txTerminos">Si usted no está de acuerdo con los Términos, no proceda a acceder a la Aplicación o a utilizar cualquiera de nuestros servicios.</p>
                  <p class="txTerminos"><span>1. Términos de uso del servicio</span></p>
                  <p class="txTerminos">La entrevista en la Aplicación, a la que usted accedió por medio de una invitación de email de una Compañía Empleadora , de aquí en adelante referida como el servicio , permite a la compañía contratante entrevistarse con Usted, el candidato , respondiendo preguntas que fueron proporcionadas por la Compañía Empleadora. Durante la entrevista en línea, usted registrará audio y video (el contenido ), que La Aplicación pondrá a disposición de la Compañía Empleadora.  La entrevista en Ventrevista.com (designada uso del servicio ) está solamente disponible para mayores de 18 años de edad. Adicionalmente, usted certifica que cualquier información que usted provea a  Ventrevista S.A. es verdadera, exacta, vigente y completa (sea por los cuestionarios, los exámenes, las formas de registro u otros medios de requerimiento de información).</p>
                  <p class="txTerminos"><span>2. Conducta del candidato:</span></p>
                  <p class="txTerminos">El servicio está específicamente diseñado para permitir a las Compañías Empleadoras entrevistar posibles candidatos utilizando la tecnología del Internet y las preguntas proporcionadas por éstas. Con este fin, le requerimos no utilizar este servicio para procesar, convertir, publicar, almacenar o compartir contenido digital prohibido. El contenido prohibido incluye pero no se limita a cualquiera de los siguientes tipos de contenido:</p>
                  <p class="txTerminos"><span>a.</span> Vídeo y/o audio grabado mientras que se usa Ventrevista que a nuestro juicio pueda parecer abusivo, engañoso, pornográfico, obsceno, difamatorio, calumnioso, ofensivo, o de cualquier manera inadecuado.</p>
                  <p class="txTerminos"><span>b.</span> Material protegido por derechos de autor y que se utiliza sin el permiso expreso del dueño.</p>
                  <p class="txTerminos"><span>c.</span> Contenido que viola o usurpa los derechos de otras personas.</p>
                  <p class="txTerminos"><span>d.</span> Cualquier material o archivo que contenga virus, o esté infectado con caballos Troyanos o cualquier forma de código corrupto que pueda comprometer el servicio de Ventrevista S.A.</p>
                  <p class="txTerminos"><span>e.</span> Cualquier contenido que promueva actividades ilegales.</p>
                  <p class="txTerminos"><span>f.</span> Cualquier contenido peligroso para menores de edad de cualquier manera.</p>
                  <p class="txTerminos"><span>g.</span> Cualquier vínculo o conexión con los anteriores.</p>
                  <p class="txTerminos">Ventrevista S.A. se reserva el derecho de determinar si el contenido es contenido prohibido, y cualquier contenido  puede ser sometido a revisión en cualquier momento. Usted acepta que aunque Ventrevista S.A.  no examina o examinará todo el contenido sometido, Ventrevista S.A. tiene el derecho absoluto (pero no la obligación) de suprimir, mover, y corregir los materiales por cualquier razón, en cualquier momento y sin previo aviso.</p>
                  <p class="txTerminos">A pesar del antedicho, cuando usted ingresa a la Aplicación,  y/o utiliza Ventrevista S.A., usted reconoce y acepta que todo el contenido (sea privado o público) que se fija y se almacena en Ventrevista S.A.  es responsabilidad única de la persona que sometió el contenido. Por ningún motivo se hará responsable a Ventrevista S.A.  o a sus funcionarios (incluyendo empleados, directivos, afiliados, agentes, asociados) por demandas de cualquier naturaleza, directas o indirectas, que tengan origen o relación con cualquier contenido que fue puesto a disposición en, o a través de Ventrevista S.A. , incluyendo pero no limitados a errores u omisiones en contenido, al igual que tampoco será Ventrevista S.A.  o sus funcionarios, responsable por y pérdidas o daños incurridos como resultado del uso de tal contenido.</p>
                  <p class="txTerminos">Usted acepta y reconoce que Ventrevista S.A., en uso de su discreción única, puede dar por concluído el uso del servicio (en todo o en parte) y remover y desechar cualquier contenido, incluyendo pero no limitado a, parte o totalidad del contenido,  información, comunicaciones, o cualquier otro contenido dentro de Ventrevista S.A., en cualquier momento, sin previo aviso, por cualquier razón, incluyendo pero no limitado a:</p>
                  <p class="txTerminos"><span>a.</span> Conducta violatoria de  estos Términos u otras políticas o pautas dispuestas por Ventrevista S.A. en cualquier lugar de la Aplicación.</p>
                  <p class="txTerminos"><span>b.</span> Conducta que Ventrevista S.A. considere dañina para otros usuarios de Ventrevista S.A.  para el negocio de Ventrevista S.A., el negocio de la Compañía Empleadora, o para proveedores de información o terceras partes.</p>
                  <p class="txTerminos"><span>c.</span> Conducta que viole los enunciados y la esencia de estos Términos. Además usted acepta que ni usted ni otra tercera persona harán responsable a Ventrevista S.A. por cualquier terminación de su acceso a la Aplicación.</p>
                  <p class="txTerminos">La Aplicación y Ventrevista S.A.  están protegidos por leyes internacionales de derechos de autor y por otras leyes aplicables. Usted acepta que cualquier uso de esta Aplicación se hará solamente con el fin de responder a una invitación legítima para una entrevista de una Compañía Empleadora. Usted acepta que no intentará  ingresar a la Aplicación con el propósito de descompilar información conducente a la creación de un sitio o servicio similar.</p>
                  <p class="txTerminos"><span>3. Autorización para utilizar el  contenido</span></p>
                  <p class="txTerminos">Para que podamos poner su entrevista a disposición de la Compañía Empleadora, Ventrevista S.A. necesita los derechos para hacer uso del vídeo y el audio que usted graba al hacer la entrevista (de acuerdo con  estos Términos). Por consiguiente, como condición para el uso de la Aplicación, por este medio, cede usted a Ventrevista S.A. los derechos para, reproducir, exhibir, modificar, transmitir, distribuir y hacer trabajos subsecuentes derivados de y con cualquier contenido transmitido o proporcionado a la Aplicación por usted, solamente con el propósito de entregar el contenido a la Compañía Empleadora para su revisión. Además, usted acepta y conoce que la Compañía Empleadora tiene el derecho de remitir el contenido sin restricción con el fin de evaluarle para un trabajo. Usted representa y garantiza a Ventrevista S.A. que usted es la persona representada en el contenido.</p>
                  <p class="txTerminos"><span>4. Reclamación por discriminación</span></p>
                  <p class="txTerminos">Usted acepta que el uso de la Aplicación, en lo que se relaciona con su derecho a no ser discriminado, no es diferente a una entrevista cara a cara o entrevista personal. Usted acepta y está de acuerdo con  QUE AL UTILIZAR ESTA APLICACIÓN  USTED SE BENEFICIA PERMITIÉNDOLE HACER UNA ENTREVISTA DE TRABAJO,  la cual, de otra manera, usted no habría tenido la oportunidad de realizar. Sus derechos para demandar por discriminación contra Ventrevista S.A. y/o la Compañía Empleadora,  ni se aumentan ni se disminuyen porque usted se entrevistó con la Aplicación.</p>
                  <p class="txTerminos"><span>5. Remisión desautorizada de contenido</span></p>
                  <p class="txTerminos">Usted conviene que no remitirá el contenido o cualquier parte del mismo a menos que sea autorizado específicamente a través de la interface de usuario en la Aplicación. Usted acepta además, que no remitirá contenido a ningún sitio público tal como YouTube, Monster, o ningún otro sitio a menos que sea autorizado explícitamente por la Aplicación.</p>
                  <p class="txTerminos"><span>6. Reventa del servicio</span></p>
                  <p class="txTerminos">Usted acuerda no reproducir, duplicar, copiar, vender, revender o explotar cualquier parte de la Aplicación, uso de la Aplicación, o el acceso a la Aplicación para cualquier propósito comercial con excepción de responder a la invitación del email que le han enviado.</p>
                  <p class="txTerminos"><span>7. Política de Privacidad</span></p>
                  <p class="txTerminos">Respetamos su privacidad, y hemos tomado medidas específicas para protegerla. Consulte, por favor, nuestra Política de Privacidad. Aun cuando tomamos medidas para solicitar a la Compañías Empleadoras que manejen el contenido de su entrevista de manera confidencial, Ventrevista S.A. no puede garantizar que así lo harán.</p>
                  <p class="txTerminos">El uso y manipulación de la aplicación vulnerando los términos de confidencialidad, puede generar riesgos para su persona que usted asume en la aceptación de las presentes condiciones, exhimiendo a Ventrevista y la compañía empleadora del tratamiento que estas hagan de los mismos siguiendo las pautas básicas del tratamiento automatizado de datos de carácter personal.</p>
                  <p class="txTerminos">Por lo tanto, usted debe responder solamente a las solicitudes de entrevista de las Compañías Empleadoras que usted ha investigado y de las cuales conoce su legitimidad y profesionalismo en el manejo de la confidencialidad.</p>
                  <p class="txTerminos"><span>8. Negación de la garantía</span></p>
                  <p class="txTerminos">USTED ACEPTA QUE EL USO DEL SERVICIO DE VENTREVISTA S.A. ES SU PROPIA CUENTA Y RIESGO. VENTREVISTA S.A. NO OFRECE  NINGUNA GARANTÍA O REPRESENTACIÓN SOBRE LA EXACTITUD O PERFECCION DEL CONTENIDO DE ESTA APLICACIÓN, O DEL CONTENIDO DE CUALQUIER SITIO WEB LIGADO A ESTA APLICACIÓN,Y NO ASUME NINGUNA RESPONSABILIDAD POR (I)EQUIVOCACIONES O ERRORES,  O INEXACTITUDES DEL CONTENIDO, (II) DAÑOS CORPORALES O DAÑO MATERIAL, DE CUALQUIER NATURALEZA COMO RESULTADO DE SU ACCESO A Y USO DE NUESTRA APLICACION, (III) CUALQUIER ACCESO A O USO DESAUTORIZADO DE NUESTROS SERVIDORES PROTEGIDOS Y/O CUALQUIER Y TODA LA INFORMACIÓN PERSONAL Y/O LA INFORMACIÓN FINANCIERA ALMACENADA EN ELLOS, (IV) CUALQUIER INTERRUPCIÓN O CESACIÓN DE LA TRANSMISIÓN A O DESDE NUESTRA APLICACION, (IV) CUALQUIER  VIRUS, CABALLOS  TROYANOS O  SIMILARES, LOS CUALES PUEDEN SER TRANSMITIDOS  A TRAVÉS DE NUESTRA APLICACIÓN POR UN TERCERO, Y/O (V) CUALQUIE ERROR U OMISION EN CUALQUIER CONTENIDO O CUALQUIER PÉRDIDA O DAÑO DE CUALQUIER CLASE OCURRIDA EN COMO RESULTADO DE SU UTILIZACION DE CUALQUIER CONTENIDO PUESTO, ENVIADO POR CORREO ELECTRONICO, TRANSMITIDO, O DE OTRA MANERA HECHO DISPONIBLE VÍA VENTREVISTA EN VENTREVISTA S.A.<p> 
                  <p class="txTerminos">VENTREVISTA S.A. NO AUTORIZA, NO ENDOSA, NO GARANTIZA, NI ASUME LA RESPONSABILIDAD DE CUALQUIER PRODUCTO O SERVICIO  ANUNCIADO U OFRECIDO POR TERCEROS A TRAVES DEL SERVICIO DE VENTREVISTA S.A.  O NINGÚN SITIO DE ENLACE U OFRECIDO EN LA MODALIDAD DE BANNER O CUALQUIER OTRA PUBLICIDAD, Y VENTREVISTA S.A. NO TOMARA PARTE O SERA DE NINGUNA MANERA RESPONSABLE DE SUPERVISAR CUALQUIER TRANSACCIÓN ENTRE USTED Y TERCEROS PROVEEDORES DE SERVICIOS Y/ O PRODUCTOS.  COMO EN LA COMPRA DE UN PRODUCTO O SERVICIO A TRAVES DE CUALUIER MEDIO O EN CUALQUIER LUGAR, USTED DEBE SER PRECAVIDO Y USAR SU BUEN JUICIO CUANDO SEA APROPIADO.</p>
                  <p class="txTerminos"><span>9. Limitación de la responsabilidad</span></p>
                  <p class="txTerminos">EN NINGUN CASO, VENTREVISTA S.A. , SUS FUNCIONARIOS, DIRECTORES, EMPLEADOS, O AGENTES, SERAN RESPONSABLES ANTE USTED POR CUALQUIER DAÑO DIRECTO, INDIRECTO, FORTUITO, ESPECIAL, PUNITIVO, O LOS DAÑOS CONSECUENTES DE CUALQUIER NATURALEZA COMO RESULTADO DE  (I)EQUIVOCACIONES O ERRORES,  O INEXACTITUDES DEL CONTENIDO, (II) DAÑOS CORPORALES O DAÑO MATERIAL, DE CUALQUIER NATURALEZA COMO RESULTADO DE SU ACCESO A Y USO DE NUESTRA APLICACION, (III) CUALQUIER ACCESO A O USO DESAUTORIZADO DE NUESTROS SERVIDORES PROTEGIDOS Y/O CUALQUIER Y TODA LA INFORMACIÓN PERSONAL Y/O LA INFORMACIÓN FINANCIERA ALMACENADA EN ELLOS, (IV) CUALQUIER INTERRUPCIÓN O CESACIÓN DE LA TRANSMISIÓN A O DESDE NUESTRA APLICACION, (IV) CUALQUIER  VIRUS, CABALLOS TROYANOS O SIMILARES, LOS CUALES PUEDEN SER TRANSMITIDOS A TRAVÉS DE NUESTRA APLICACIÓN POR UN TERCERO, Y/O (V) CUALQUIE ERROR U OMISION EN CUALQUIER CONTENIDO O CUALQUIER PÉRDIDA O DAÑO DE CUALQUIER CLASE OCURRIDA EN COMO RESULTADO DE SU UTILIZACION DE CUALQUIER CONTENIDO PUESTO, ENVIADO POR CORREO ELECTRONICO, TRANSMITIDO, O DE OTRA MANERA HECHO DISPONIBLE VÍA LA ENTREVISTA EN VENTREVISTA S.A, YA SEAN SOPORTADOS POR GARANTIA, CONTRATO, AGRAVIO, O CUALQUIER OTRA TEORÍA LEGAL, Y AUNQUE LA COMPAÑÍA TENGA CONOCIMIENTO DE LA POSIBILIDAD DE TALES DAÑOS. LA LIMITACIÓN DE LA RESPONSABILIDAD PRECEDENTE SE APLICARÁ CON TODO EL ALCANCE DE LA LEY EN LA JURISDICCIÓN CORRESPONDIENTE.</p>
                  <p class="txTerminos">USTED RECONOCE ESPECÍFICAMENTE QUE VENTREVISTA S.A.  NO SERÁ RESPONSABLE POR LAS PROPUESTAS DE LOS USUARIOS O LA CONDUCTA DIFAMATORIA, OFENSIVA, O ILEGAL DE CUALQUIER TERCERO Y EL RIESGO CUALQUIER DAÑO O MENOSCABO COMO CONSECUENCIA DE LOS ANTERIORES RECAE ENTERAMENTE EN USTED.</p>
                  <p class="txTerminos"><span>10. Indemnización</span></p>
                  <p class="txTerminos">Usted acepta defender, indemnizar y mantener fuera de peligro a Ventrevista S.A., sus socios, funcionarios, directivos, empleados y agentes  por cualquier tipo de demanda, daños, obligaciones, pérdidas, responsabilidades, deudas, y costas (que incluyen pero no se limitan a los honorarios del abogado) que se derivan de: (i) su uso y acceso la Aplicación de Ventrevista S.A.; (ii) su violación de cualquier término de estos Términos del Servicio; (iii) su violación de cualquier derecho de terceros, incluyendo sin limitación alguna violación a los derechos de autor, propiedad y derecho a la privacidad;  o (iv) cualquier reclamación de que su contenido ha causado daños a terceros. Esta obligación a la defensa e indemnización,  prevalecerá estos Términos del Servicio y su uso de la Aplicación en Ventrevista S.A.</p>
                  <p class="txTerminos"><span>11. Capacidad de aceptar términos del servicio</span></p>
                  <p class="txTerminos">Usted afirma que, o tiene más de 18 años de edad, o es un menor de edad emancipado, o tiene consentimiento de sus padres o guardián legal, y es completamente capaz y competente de aceptar los términos, las condiciones, las obligaciones, las afirmaciones, las representaciones, y las garantías dispuestas en estos Términos del Servicio, y se atiene y compromete a cumplir con Términos del Servicio. Si usted es menor de 18 años de edad, por favor no utilice la entrevista de Ventrevista S.A.</p>
                  <p class="txTerminos"><span>12. Cesión</span></p>
                  <p class="txTerminos">Estos Términos del Servicio, y todos los derechos y licencias concedidas aquí, no se pueden transferir o ceder por usted, pero sí pueden ser cedidos por Ventrevista S.A. sin ninguna restricción.</p>
                  <p class="txTerminos"><span>13. General</span></p>
                  <p class="txTerminos">Usted acepta que estos Términos, junto con la política de privacidad en Política de Privacidad y cualquier otro aviso legal publicado por Ventrevista S.A., constituirá el acuerdo entre usted y Ventrevista S.A. referente al servicio de entrevista de Ventrevista S.A.  Si alguna disposición de estos Términos del Servicio es declarada nula o anulable, la invalidez de tal disposición no afectará la validez de las provisiones restantes de estos Términos del Servicio, los cuales permanecerán en vigor y efecto. No se juzgará ninguna renuncia de ningún término de estos Términos del Servicio y la continuación de la  renuncia de tal término o de cualquier otro término, y la falta de Ventrevista S.A. de hacer valer cualquier término de estos Términos del servicio no constituirá una renuncia de tal derecho o disposición. Ventrevista S.A. S se reserva el derecho de enmendar estos Términos del Servicio en cualquier momento y sin previo aviso, y es su responsabilidad revisar estos Términos del Servicio por cualquier cambio. El uso que usted haga de la entrevista de Ventrevista S.A. después de cualquier enmienda de estos Términos del Servicio significará su consentimiento y aceptación de los Términos revisados. Usted acepta,  que sin importar cualquier estatuto o ley que lo contradiga, cualquier demanda o reclamo a causa  o relacionado con el uso de la Aplicación o de los Términos se debe interponer dentro del siguiente (1) año a la fecha de ocurrencia o será para siempre excluida.</p>
                  <p class="txTerminos"><span>14. Proteccion de datos personales</span></p>
                  <p class="txTerminos">Para utilizar o tener acceso a alguno de los contenidos y/o servicios del presente portal, Ventrevista España, S.L. (Ventrevista España, S.L., mercantil Española domiciliada en C/Diputación, 279, 1º planta, 08007 Barcelona, con CIF B65411688 actúa en España como comercializadora de Ventrevista, S.A.) podrá solicitar la cumplimentación de formularios que implican el tratamiento de datos de carácter personal.</p>
                  <p class="txTerminos">En cumplimiento de lo dispuesto en la Ley Orgánica 15/1999, de 13 de diciembre, de Protección de Datos de Carácter Personal, su Reglamento de Desarrollo aprobado mediante Real Decreto 1720/2007 de 21 de diciembre, la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico y la Ley 1/1982 de 5 de mayo, de protección civil del honor, la intimidad y la propia imagen, Ventrevista España S.L. le informa que los datos personales que nos comunique en cualquier acto, incluida su dirección electrónica, imagen y voz, así como aquellos datos sobre los cuales Ventrevista España, S.L. tenga acceso como consecuencia de los registros electrónicos así como de la navegación, consulta, solicitud o contratación, o de cualquier transacción u operación realizada desde este sitio Web o de los que se pudiesen derivar de la relación establecida con el usuario, incluso después de su finalización, serán tratadas en el correspondiente fichero de Ventrevista España, S.L. que cumple con las exigencias de la legislación vigente aplicable y que se encuentra debidamente inscrito al Registro General de la Agencia Española de Protección de Datos.</p>
                  <p class="txTerminos">La recogida y tratamiento de los datos personales de los usuarios tiene como finalidad la prestación de los servicios que Ventrevista España, S.L. proporciona a través de este sitio Web, consistente en la grabación de video entrevistas para cubrir una vacante, así como el mantenimiento de la relación establecida, su gestión, administración, ampliación y mejora.</p>
                  <p class="txTerminos">Además sus datos personales serán tratados con finalidades publicitarias y de prospección comercial para remitirle, por cualquier medio, incluido el correo postal o electrónico, SMS y cualquier otro medio equivalente, información de futuras vacantes en el cargo o proceso interesado, actividades, cursos, servicios y otros acontecimientos ofrecidos por Ventrevista España S.L. o por terceros. Si no desea que se traten sus datos con esta finalidad, marque aquí.</p>
                  <p class="txTerminos">El usuario declara que toda la información que suministra es veraz, exacta y completa y se compromete a mantenerla actualizada y a comunicar todos los cambios de forma inmediata. En aquellos supuestos en que el usuario facilitase datos personales de otras personas físicas, éste asume la obligación de observar, respeto a los citados datos, las exigencias derivadas de la Ley Orgánica 15/1999, de 13 de diciembre (LOPD), específicamente, de los deberes de calidad, información y de solicitud del consentimiento a las personas titulares de los datos personales que le conciernen para su tratamiento.</p>
                  <p class="txTerminos">Mediante la cumplimentación del formulario de registro y su aceptación mediante el cliqueo del botón, así como la remisión de cualquier información a través de cualquier tipo de formularios electrónicos o por correo electrónico, fax, sms, etc. el usuario manifiesta expresa e inequívocamente su consentimiento para que los datos de carácter personal suministrados, sean incorporados al fichero correspondiente y tratados con las finalidades indicadas.</p>
                  <p class="txTerminos">Así mismo, el usuario presta expresamente su consentimiento para la cesión o comunicación y transferencia internacional de sus datos personales por parte de Ventrevista España, S.L., a  Ventrevista, S.A. y a la sociedad Rackspace, US Inc que se dedica a la prestación de servicios de hosting ubicada en 5000 Walzem Road, San Antonio, TX 78218, de Estados Unidos de América, entidad ésta dónde está alojado este Sitio Web y las ventrevistas, así como los datos personales y las video entrevistas objeto del servicio prestado a los usuarios. En este sentido, Ventrevista España, S.L. pone en conocimiento del usuario que sin la prestación del consentimiento para la citada transferencia internacional, no podrá perfeccionarse el contrato, ni por tanto, prestarse el servicio de video entrevista.</p>
                  <p class="txTerminos">Ventrevista España, S.L. se reserva la facultad, que expresamente le reconoce el usuario, de modificar el país dónde están alojados los datos personales ya sea por motivos técnicos, organizativos o de cualquier otra índole. En tal caso, Ventrevista España, S.L. solicitará nuevamente el consentimiento previo al usuario, si ese requisito es exigido por la legislación vigente.</p>
                  <p class="txTerminos">Los usuarios que hayan facilitado sus datos podrán dirigirse a Ventrevista España, S.L., como responsable del fichero para ejercitar los derechos los derechos de acceso, rectificación o cancelación de datos y oposición del uso, cesión o transferencia internacional de los datos, así como el derecho de revocar el consentimiento prestado, derechos que podrán ser ejercitados por el usuario o, en su caso, por quién lo represente, mediante solicitud escrita, firmada y escaneada a la dirección de correo info@ventrevista.es. La solicitud deberá contener los siguientes datos: nombre y apellidos del usuario, domicilio a efectos de notificaciones, fotocopia del Documento Nacional de Identidad o pasaporte, y contenido concreto del derecho ejercitado.</p>
                  <p class="txTerminos">Pese a que Ventrevista España, S.L. declara haber adoptado aquellas medidas de seguridad, tanto técnicas como organizativas, necesarias para garantizar la confidencialidad e integridad de los datos tratados y manifiesta cumplir con aquellas medidas establecidas en el Real Decreto 1720/2007, de 21 de diciembre, relativas a las medidas de seguridad de los ficheros que contengan datos de carácter personal de acuerdo con el nivel de los datos almacenados, el usuario debe ser consciente de que las medidas de seguridad en Internet no son inexpugnables.</p>
                  <p class="txTerminos"><span>15. Modificación de términos</span></p>
                  <p class="txTerminos">Usted acepta que Ventrevista S.A. se reserva el derecho de enmendar los Términos en cualquier momento, por cualquier razón, y sin previo aviso, incluyendo el derecho de terminar el servicio o cualquier parte del mismo. Cualquier enmienda o modificación hecha por Ventrevista S.A. será hacia el futuro solamente.</p>
                </div> 
            </div>
        </div>

    </body>
</html>
