
//VIDEO GALLERY
(function(n){n.fn.vGallery=function(a){a=n.extend({menuWidth:100,menuHeight:350,menuSpace:0,randomise:"off",autoplay:"off",autoplayNext:"on",menu_position:"right",menuitem_width:"200",menuitem_height:"71",menuitem_space:"0",transition_type:"slideup",design_skin:"skin_default",videoplayersettings:"",embedCode:"",shareCode:"",responsive:"off"},a);this.each(function(){function A(){r=t.width();var a="scale("+r/f+")";c.get(0).var_scale=r/f;var b=r/f*i;r<f?(c.css({"-moz-transform":a,transform:a,"-webkit-transform":a,
"-o-transform":a}),t.css({height:b})):(c.css({"-moz-transform":"","-webkit-transform":"","-o-transform":""}),t.css({height:"auto"}))}function B(a,b){var a=parseInt(Math.random()*b),c=0;for(j=0;j<m.length;j++)a==m[j]&&(c=1);if(1==c)B(0,b);else return m.push(a),a}function D(b){!1==is_ios()&&(("right"==a.menu_position||"left"==a.menu_position)&&k.css({top:-((b.pageY-l.offset().top)/i*((a.menuitem_height+a.menuitem_space)*d-i))}),("bottom"==a.menu_position||"top"==a.menu_position)&&k.css({left:-((b.pageX-
l.offset().left)/f*((a.menuitem_width+a.menuitem_space)*d-f))}))}function E(a){u(k.children().index(a.currentTarget))}function u(b){function f(){c.parent().children(".preloader").fadeOut("fast");"fade"==a.transition_type&&(e.children().eq(b).css({left:0,top:0}),-1<h&&e.children().eq(h).animate({opacity:"0"},1E3),e.children().eq(b).css({opacity:"0"}),e.children().eq(b).animate({opacity:"1"},1E3));"slideup"==a.transition_type&&(-1<h&&(e.children().eq(h).animate({left:0,top:0},0),e.children().eq(h).animate({left:0,
top:-i},700)),e.children().eq(b).animate({left:0,top:i},0),e.children().eq(b).animate({left:0,top:0},700));is_ios()&&-1<h&&"VIDEO"==e.children().eq(h).children().eq(0)[0].tagName&&e.children().eq(h).children().eq(0).get(0).pause();!is_ios()&&!is_ie8()&&-1<h&&void 0!=e.children().eq(h).get(0).externalPauseMovie&&e.children().eq(h).get(0).externalPauseMovie();x=!1;h=b}if(!(h==b||!0==x)){var g=!1,d=e.children().eq(b),k=d.parent().children().index(d);d.hasClass("vplayer-tobe")&&(g=!0,a.videoplayersettings.videoWidth=
o,a.videoplayersettings.videoHeight=v,a.videoplayersettings.responsive="off","on"==a.autoplay&&0==k&&(a.videoplayersettings.autoplay="on"),"on"==a.autoplayNext&&0<k&&(a.videoplayersettings.autoplay="on"),d.vPlayer(a.videoplayersettings));x=!0;-1==h||!1==g?f():(c.parent().children(".preloader").fadeIn("fast"),setTimeout(f,1E3))}}function F(){!1==y?(g.find(".embed-button .contentbox").animate({right:60},{queue:!1,duration:300}),g.find(".embed-button .contentbox").fadeIn("fast"),y=!0):(g.find(".embed-button .contentbox").animate({right:50},
{queue:!1,duration:300}),g.find(".embed-button .contentbox").fadeOut("fast"),y=!1)}function G(){!1==z?(g.find(".share-button .contentbox").animate({right:60},{queue:!1,duration:300}),g.find(".share-button .contentbox").fadeIn("fast"),z=!0):(g.find(".share-button .contentbox").animate({right:50},{queue:!1,duration:300}),g.find(".share-button .contentbox").fadeOut("fast"),z=!1)}var c=jQuery(this);n(this)[0].getAttribute("id");var d=0,p,e,l,k,o,v,f,i,m=[],C=[],h=-1,t,r=0,q=0,w=0,x=!1,y=!1,z=!1;a.menuitem_width=
parseInt(a.menuitem_width);a.menuitem_height=parseInt(a.menuitem_height);a.menuitem_space=parseInt(a.menuitem_space);d=jQuery(this).children().length;o=parseInt(jQuery(this).css("width"));v=parseInt(jQuery(this).css("height"));f=o;i=v;c.get(0).var_scale=1;if(("right"==a.menu_position||"left"==a.menu_position)&&1<d)f+=a.menuitem_width+a.menuSpace;if(("bottom"==a.menu_position||"top"==a.menu_position)&&1<d)i+=a.menuitem_height+a.menuSpace;c.addClass(a.design_skin);a.videoplayersettings.design_skin=
a.design_skin;a.videoplayersettings.videoGalleryCon=c.get(0);0==c.css("opacity")&&c.animate({opacity:1},1E3);t=c.parent().hasClass("videogallery-con")?c.parent().parent():c.parent();c.parent().children(".preloader").fadeOut("fast");for(b=0;b<d;b++)C[b]=jQuery(this).children().eq(b),"on"==a.randomise?B(0,d):m[b]=b;c.append('<div class="sliderMain"><div class="sliderCon"></div></div>');c.append('<div class="navMain"><div class="navCon"></div></div>');p=jQuery(this).find(".sliderMain");e=jQuery(this).find(".sliderCon");
is_ie8()&&e.addClass("sliderCon-ie8");l=jQuery(this).find(".navMain");k=jQuery(this).find(".navCon");c.css({width:f,height:i});c.parent().hasClass("videogallery-con")&&c.parent().css({width:f,height:i});for(b=0;b<d;b++){var s=c.children().eq(m[b]).find(".menuDescription").html();c.children().eq(m[b]).find(".menuDescription").remove();null!=s&&(-1<s.indexOf("{ytthumb}")&&(s=s.split("{ytthumb}").join('<img src="http://img.youtube.com/vi/'+c.children().eq(m[b]).attr("data-src")+'/0.jpg" class="imgblock"/>')),
k.append('<div><div class="navigationThumb-content">'+s+"</div></div>"),k.children().eq(b).addClass("navigationThumb"),k.children().eq(b).css({width:a.menuitem_width,height:a.menuitem_height}),k.children().eq(b).click(E),"right"==a.menu_position||"left"==a.menu_position?k.children().eq(b).css({top:w}):k.children().eq(b).css({left:q}),w+=a.menuitem_height+a.menuitem_space,q+=a.menuitem_width+a.menuitem_space)}for(var b=0,b=0;b<d;b++)e.append(C[m[b]]);for(b=0;b<d;b++)is_ios();for(b=0;b<d;b++)e.children().eq(b).css({position:"absolute",
top:"0px",left:q}),q+=f;p.css({width:f,height:i});"right"==a.menu_position&&l.css({width:a.menuitem_width,height:i,left:o});"left"==a.menu_position&&(l.css({width:a.menuitem_width,height:i,left:0}),p.css({left:a.menuitem_width}));"bottom"==a.menu_position&&l.css({width:f,height:a.menuitem_height,top:v,left:0});"top"==a.menu_position&&(l.css({width:f,height:a.menuitem_height,top:0,left:0}),p.css({top:a.menuitem_height}));is_ios()&&l.css("overflow","auto");0!=a.menuSpace&&l.css({left:o+a.menuSpace});
k.css({position:"relative"});jQuery(".navigationThumb").eq(0).height()*d>i&&l.mousemove(D);w=0;1==d&&(jQuery(this).css({width:o}),l.hide());c.get(0).videoEnd=function(){var a=h+1;a>=e.children().length&&(a=0);u(a)};u(0);""!=a.logo&&c.append('<img class="the-logo" src="'+a.logo+'"/>');c.append('<div class="gallery-buttons"></div>');var g=c.children(".gallery-buttons");""!=a.embedCode&&(g.append('<div class="embed-button"><div class="handle"></div><div class="contentbox" style="display:none;"><textarea class="thetext">'+
a.embedCode+"</textarea></div></div>"),g.find(".embed-button .handle").click(F),g.find(".embed-button .contentbox").css({right:50}));""!=a.shareCode&&(g.append('<div class="share-button"><div class="handle"></div><div class="contentbox" style="display:none;"><div class="thetext">'+a.shareCode+"</div></div></div>"),g.find(".share-button .handle").click(G),g.find(".share-button .contentbox").css({right:50}));"right"==a.menu_position&&(g.css({right:a.menuitem_width+parseInt(a.menuSpace,10)}),0<c.find(".the-logo").length&&
c.find(".the-logo").css({right:a.menuitem_width+parseInt(a.menuSpace,10)+60}));"on"==a.responsive&&(jQuery(window).bind("resize",A),A());setInterval(function(){},5E3);n.fn.turnFullscreen=function(){jQuery(this).css({position:"static"});p.css({position:"static"})};n.fn.turnNormalscreen=function(){jQuery(this).css({position:"relative"});p.css({position:"relative"});for(b=0;b<d;b++)e.children().eq(b).css({position:"absolute"})};n.fn.vGallery.gotoItem=function(a){u(a)};return this})}})(jQuery);





//VIDEO PLAYER
var ytplayer,$=jQuery.noConflict();
(function(h){h.fn.vPlayer=function(b){b=h.extend({type:"normal",autoplay:"off",videoWidth:0,videoHeight:0,constrols_out_opacity:0,constrols_normal_opacity:0.9,design_scrubbarWidth:-201,insideGallery:!1,design_skin:"skin_default",design_background_offsetw:0,cueVideo:"on",videoGalleryCon:null},b);this.each(function(){function K(){var a=c;a.unbind();a.attr("data-type");L=a.attr("data-src");o=a.attr("data-sourceflash");c.find(".preview").fadeOut("fast");void 0==a.attr("data-sourceflash")&&(o=a.attr("data-sourcemp4"));
"audio"==b.type&&(void 0!=a.attr("data-sourcemp3")&&void 0==a.attr("data-sourceflash"))&&(o=a.attr("data-sourcemp3"));if(is_ie8()){a.find(".controls").remove();a.addClass("vplayer-ie8");"normal"==b.type&&a.prepend('<div><object type="application/x-shockwave-flash" data="preview.swf" width="'+f+'" height="'+g+'" id="flashcontent" style="visibility: visible;"><param name="movie" value="preview.swf"><param name="menu" value="false"><param name="allowScriptAccess" value="always"><param name="scale" value="noscale"><param name="allowFullScreen" value="true"><param name="wmode" value="opaque"><param name="flashvars" value="video='+
o+'"></object></div>');"audio"==b.type&&a.prepend('<div><object type="application/x-shockwave-flash" data="preview.swf" width="'+f+'" height="'+g+'" id="flashcontent" style="visibility: visible;"><param name="movie" value="preview.swf"><param name="menu" value="false"><param name="allowScriptAccess" value="always"><param name="scale" value="noscale"><param name="allowFullScreen" value="true"><param name="wmode" value="opaque"><param name="flashvars" value="video='+o+'&types=audio"></object></div>');
if("vimeo"==b.type){var e=a.attr("data-src");a.append('<iframe width="'+f+'" height="'+g+'" src="http://player.vimeo.com/video/'+e+'" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen style="width:'+f+"px; height:"+g+'px;"></iframe>')}"youtube"==b.type&&(b.type="youtube",a.children().remove(),e="ytplayer"+L,a.append('<iframe width="'+f+'" height="'+g+'" src="http://www.youtube.com/embed/'+a.attr("data-src")+'" frameborder="0" allowfullscreen></iframe>'),a.attr("data-ytid",e))}else is_ios()?
("normal"==b.type&&(a.prepend("<video controls preload></video>"),a.children().eq(0).attr("width",f),a.children().eq(0).attr("height",g),void 0!=a.attr("data-sourcemp4")&&a.children().eq(0).append('<source src="'+a.attr("data-sourcemp4")+'" type="video/mp4"/>')),"audio"==b.type&&(a.prepend("<audio controls preload></audio>"),a.children().eq(0).attr("width",f),a.children().eq(0).attr("height",g),void 0!=a.attr("data-sourcemp3")&&a.children().eq(0).append('<source src="'+a.attr("data-sourcemp3")+'" type="audio/mp3" style="width:'+
f+"px; height:"+g+'px;"/>')),"youtube"==b.type&&(b.type="youtube",a.children().remove(),a.append('<iframe src="http://www.youtube.com/embed/'+a.attr("data-src")+'" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowfullscreen style="width:'+f+"px; height:"+g+'px;"></iframe>')),"vimeo"==b.type&&(a.children().remove(),e=a.attr("data-src"),a.append('<iframe width="'+f+'" height="'+g+'" src="http://player.vimeo.com/video/'+e+'" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen style="width:'+
f+"px; height:"+g+'px;"></iframe>')),c.children(".controls").remove(),F()):(!is_ie8()&&!is_ios()&&("audio"==b.type&&void 0!=a.attr("data-audioimg")&&(e='<img src="'+a.attr("data-audioimg")+'" width="'+f+'" height="'+g+'" class="audioImg"/>',a.prepend(e)),"normal"==b.type&&(e="<video controls preload",0!=f&&(e+=' width="'+f+'"',e+=' height="'+g+'"'),e+="></video>",is_ie9()||a.prepend(e),void 0!=a.attr("data-sourcemp4")&&(a.children().eq(0).append('<source src="'+a.attr("data-sourcemp4")+'" type="video/mp4"/>'),
is_ie9()&&(a.find(".controls"),a.prepend('<video controls preload><source src="'+a.attr("data-sourcemp4")+'" type="video/mp4"/></video>'))),void 0!=a.attr("data-sourceogg")&&(a.children().eq(0).append('<source src="'+a.attr("data-sourceogg")+'" type="video/ogg"/>'),a.attr("data-sourceogg")),void 0!=a.attr("data-sourcewebm")&&(a.children().eq(0).append('<source src="'+a.attr("data-sourcewebm")+'" type="video/webm"/>'),a.attr("data-sourcewebm")),void 0!=a.attr("data-sourceflash")&&!(h.browser.msie&&
8<h.browser.version)&&a.children().eq(0).append('<object type="application/x-shockwave-flash" data="preview.swf" width="'+f+'" height="'+g+'" id="flashcontent" style="visibility: visible;"><param name="movie" value="preview.swf"><param name="menu" value="false"><param name="allowScriptAccess" value="always"><param name="scale" value="noscale"><param name="allowFullScreen" value="true"><param name="wmode" value="opaque"><param name="flashvars" value="video='+o+'"></object>')),"audio"==b.type&&(e="<audio controls",
0!=f&&(e+=' width="'+f+'"',e+=' height="'+g+'"'),a.prepend(e+"></audio>"),void 0!=a.attr("data-sourcemp3")&&(a.children().eq(0).append('<source src="'+a.attr("data-sourcemp3")+'" type="audio/mp3"/>'),is_ie9()&&a.html('<audio><source src="'+a.attr("data-sourcemp3")+'" type="audio/mp3"/></audio>')),void 0!=a.attr("data-sourceogg")&&a.children().eq(0).append('<source src="'+a.attr("data-sourceogg")+'" type="audio/ogg"/>'),void 0!=a.attr("data-sourcewav")&&a.children().eq(0).append('<source src="'+a.attr("data-sourcewav")+
'" type="audio/wav"/>'),void 0!=a.attr("data-sourceflash")&&!(h.browser.msie&&8<h.browser.version)&&a.children().eq(0).append('<object type="application/x-shockwave-flash" data="preview.swf" width="'+f+'" height="'+g+'" id="flashcontent" style="visibility: visible;"><param name="movie" value="preview.swf"><param name="menu" value="false"><param name="allowScriptAccess" value="always"><param name="scale" value="noscale"><param name="allowFullScreen" value="true"><param name="wmode" value="opaque"><param name="flashvars" value="video='+
o+'&types=audio"></object>')),"youtube"==b.type&&(e="ytplayer"+a.attr("data-src"),a.prepend('<object type="application/x-shockwave-flash" data="http://www.youtube.com/apiplayer?enablejsapi=1&version=3&playerapiid='+e+'" width="'+f+'" height="'+g+'" id="'+e+'" style="visibility: visible;"><param name="movie" value="http://www.youtube.com/apiplayer?enablejsapi=1&version=3"><param name="menu" value="false"><param name="allowScriptAccess" value="always"><param name="scale" value="noscale"><param name="allowFullScreen" value="true"><param name="wmode" value="opaque"><param name="flashvars" value=""></object>'),
a.attr("data-ytid",e)),"vimeo"==b.type&&(e=a.attr("data-src"),c.children(".controls").remove(),a.prepend('<iframe src="http://player.vimeo.com/video/'+e+"?api=1&player_id=vimeoplayer"+e+'" width="'+f+'" height="'+g+'" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>'))),0==c.css("opacity")&&c.animate({opacity:1},1E3),"normal"==b.type&&(d=c.children("video").eq(0)[0],d.controls=!1),"audio"==b.type&&(d=c.children("audio").eq(0)[0],d.controls=!1),"youtube"==b.type&&
(d=c.children("object")[0]),"vimeo"==b.type&&(d=c.children("iframe")[0],window.addEventListener&&window.addEventListener("message",R,!1)),"normal"==b.type&&h(d).css({position:"absolute","background-color":"#000000"}),"on"==G&&(w=!0),x=setInterval(S,50),c.get(0).externalPauseMovie=y)}function S(){if("youtube"==b.type&&d.getPlayerState){if(is_ie8()){clearInterval(x);setTimeout(z,1E3);return}-1<d.getPlayerState()&&(clearInterval(x),z())}if(("normal"==b.type||"audio"==b.type)&&3<=Number(d.readyState))clearInterval(x),
z();jQuery.browser.opera&&("audio"==b.type&&2==Number(d.readyState))&&z()}function z(){function a(a){var e=c.find(".volumecontrols").children();0<=a&&("normal"==b.type&&(d.volume=a),"youtube"==b.type&&d.setVolume(100*a));e.eq(2).width(a*e.eq(1).width());null!=localStorage&&localStorage.setItem("volumeIndex",a)}function e(a){var a=Math.round(a),b=0;if(0<a){for(;59<a;)b++,a-=60;return""+((10>b?"0":"")+b+":"+(10>a?"0":"")+a)}return"00:00"}null!=localStorage&&(M=null===localStorage.getItem("volumeIndex")?
1:localStorage.getItem("volumeIndex"));0==f&&(f=h(d).width(),g=h(d).height());s(f,g);a(M);setInterval(function(){scrubbar=c.find(".scrubbar");var a=-1;if(b.type=="normal"||b.type=="audio"){n=d.duration;A=d.currentTime;a=d.buffered.end(0)/d.duration*scrubbar.children().eq(0).width()}if(b.type=="youtube"){if(d.getDuration){n=d.getDuration();A=d.getCurrentTime()}a=d.getVideoBytesLoaded()/d.getVideoBytesTotal()*scrubbar.children().eq(0).width();q=d.getVideoStartBytes()/d.getVideoBytesTotal()*scrubbar.children().eq(0).width();
scrubbar.children(".scrub-buffer").css("left",q)}q=A/n*scrubbar.children().eq(0).width();scrubbar.children(".scrub").width(q);a>-1&&scrubbar.children(".scrub-buffer").width(a);c.find(".timetext").html('<font color="#FFFFFF" size="1px">'+e(A)+'</font><font color="gray" size="1px">/'+e(n)+"</font>")},100);"on"==G&&t();c.mouseout(function(){k.animate({opacity:b.constrols_out_opacity},{queue:false,duration:200})});c.mouseover(function(){k.animate({opacity:b.constrols_normal_opacity},{queue:false,duration:200})});
p.click(N);c.find(".volumecontrols").click(function(e){j=c.find(".volumecontrols").children();if(e.pageX-j.eq(1).offset().left>=0){q=e.pageX-j.eq(1).offset().left;j.eq(2).css("visibility","visible");j.eq(3).css("visibility","hidden");a(q/j.eq(1).width())}else if(j.eq(3).css("visibility")=="hidden"){B=d.volume;if(b.type=="normal")d.volume=0;b.type=="youtube"&&d.setVolume(0);j.eq(3).css("visibility","visible");j.eq(2).css("visibility","hidden")}else{console.log(B);if(b.type=="normal")d.volume=B;b.type==
"youtube"&&d.setVolume(B);j.eq(3).css("visibility","hidden");j.eq(2).css("visibility","visible")}});scrubbar.bind("click",function(a){scrubbar=c.find(".scrubbar");w==false?y():t();if(b.type=="normal"||b.type=="audio"){n=d.duration;d.currentTime=(a.pageX-scrubbar.offset().left)/scrubbar.children().eq(0).width()*n}if(b.type=="youtube"){n=d.getDuration();d.seekTo((a.pageX-scrubbar.offset().left)/scrubbar.children().eq(0).width()*n)}});i.click(O);c.keypress(T);("normal"==b.type||"audio"==b.type)&&d.addEventListener("ended",
P,!1)}function P(){1==u&&N();if("normal"==b.type||"audio"==b.type)d.currentTime=0,d.pause();"youtube"==b.type&&d.seekTo(0);null!=b.videoGalleryCon&&b.videoGalleryCon.videoEnd()}function F(){if(is_ios()&&void 0!=H){var a=H.get(0).var_scale;c.children("iframe").width(1/a*f);c.children("iframe").height(1/a*g)}if("on"==b.responsive){C=D.width();var a="scale("+C/l+")",d=C/l*m;C<l?(c.css({"-moz-transform":a,transform:a,"-webkit-transform":a,"-o-transform":a}),D.css({height:d})):(c.css({"-moz-transform":"",
"-webkit-transform":"","-o-transform":""}),D.css({height:"auto"}))}1===u&&(l=h(window).width(),m=h(window).height(),s(l,m),0<c.find(".audioImg").length&&c.find(".audioImg").css({width:l,height:m}))}function T(a){32==a.charCode&&O()}function R(a){var b;v="";v=jQuery(d).attr("src").split("?")[0];try{b=JSON.parse(a.data)}catch(c){}"ready"==b.event&&(t(),r={method:"addEventListener",value:"finish"},d.contentWindow.postMessage(JSON.stringify(r),v))}function O(){E=!1;if(("normal"==b.type||"audio"==b.type)&&
d.paused)E=!0;"youtube"==b.type&&(d.getPlayerState&&2==d.getPlayerState())&&(E=!0);is_ie8()?I?(t(),I=!1):(y(),I=!0):E?t():y()}function N(){var a=c.get(0);l=h(window).width();m=h(window).height();0==u?(u=1,a.requestFullScreen?a.requestFullScreen():a.mozRequestFullScreen?a.mozRequestFullScreen():a.webkitRequestFullScreen&&a.webkitRequestFullScreen(),jQuery("body").css("overflow","hidden"),l=h(window).width(),m=h(window).height(),c.css({position:"fixed","z-index":9999,left:"0px",top:"0px",width:l,height:m}),
s(l,m),0<c.find(".audioImg").length&&c.find(".audioImg").css({width:l,height:m}),!0==b.insideGallery&&jQuery(this).parent().parent().parent().parent().parent().turnFullscreen()):(u=0,a=document,a.cancelFullScreen?a.cancelFullScreen():a.mozCancelFullScreen?a.mozCancelFullScreen():a.webkitCancelFullScreen&&a.webkitCancelFullScreen(),h("body").css("overflow",Q),c.css({position:"relative","z-index":"auto",left:"0px",top:"0px",width:f,height:g}),s(f,g),0<c.find(".audioImg").length&&c.find(".audioImg").css({width:f,
height:g}),!0==b.insideGallery&&jQuery(this).parent().parent().parent().parent().parent().turnNormalscreen())}function s(a,e){c.css({width:a,height:e});h(d).css({width:a,height:e});c.find(".background").css({width:a+parseInt(b.design_background_offsetw)});c.find(".preview").children().eq(0).css({width:a,height:e});k.css({width:a});is_ie8()&&k.css({position:"absolute",top:0,left:0});scrubbar=c.find(".scrubbar").children();scrubbar.eq(0).width(a+b.design_scrubbarWidth);parseInt(k.find(".infoText").css("left"));
parseInt(k.find(".infoText").css("top"))}function t(){"vimeo"==b.type?(r={method:"play"},d.contentWindow.postMessage(JSON.stringify(r),v)):(i.children().eq(0).css("visibility","hidden"),i.children().eq(1).css("visibility","hidden"),i.children().eq(2).css("visibility","visible"),i.children().eq(3).css("visibility","visible"),("normal"==b.type||"audio"==b.type)&&d.play(),"youtube"==b.type&&d.playVideo(),c.children(".video-description").animate({opacity:0},500),w=!0)}function y(){i.children().eq(0).css("visibility",
"visible");i.children().eq(1).css("visibility","visible");i.children().eq(2).css("visibility","hidden");i.children().eq(3).css("visibility","hidden");("normal"==b.type||"audio"==b.type)&&d.pause();"youtube"==b.type&&d.pauseVideo&&d.pauseVideo();"vimeo"==b.type?/Opera/.test(navigator.userAgent)||(r={method:"pause"},d.contentWindow.postMessage(JSON.stringify(r),v)):(c.children(".video-description").animate({opacity:1},500),w=!1)}var c,k,f,g,l,m,d,q=0,u=0,x,B,M,w=!1,G="off",j,p,i,E=!1,I=!0,n=0,A=0,o=
"",L="",J="",Q="auto;",C,D,H,r,v;c=jQuery(this);h(this)[0].getAttribute("id");Q=h("body").css("overflow");c.parent().parent().parent().hasClass("videogallery")&&(H=c.parent().parent().parent());G=b.autoplay;f=b.videoWidth;g=b.videoHeight;(function(){if(c.hasClass("vplayer-tobe")){var a=c;a.removeClass("vplayer-tobe");a.addClass("vplayer");a.addClass(b.design_skin);"youtube"==a.attr("data-type")&&(b.type="youtube");"vimeo"==a.attr("data-type")&&(b.type="vimeo");"image"==a.attr("data-type")&&(b.type=
"image");"audio"==a.attr("data-type")&&(b.type="audio");D=c.parent();c.append('<div class="controls"></div>');k=c.find(".controls");k.css("opacity",b.constrols_normal_opacity);l=f;m=g;c.css({width:f,height:g});void 0!=c.attr("data-videoTitle")&&(c.append('<div class="video-description"></div>'),c.children(".video-description").append('<div class="video-title">'+c.attr("data-videoTitle")+"</div>"),""!=J&&c.children(".video-description").append('<div class="video-subdescription">'+J+"</div>"),c.find(".video-subdescription").css("width",
0.7*f));"absolute"!=c.css("position")&&c.css("position","relative");"vimeo"!=b.type&&"image"!=b.type&&(k.append('<div class="background"></div>'),k.append('<div class="playcontrols"></div>'),k.append('<div class="scrubbar"></div>'),k.append('<div class="timetext"></div>'),k.append('<div class="volumecontrols"></div>'),k.append('<div class="fscreencontrols"></div>'));"image"==b.type&&c.attr("data-img",c.attr("data-source"));void 0!=c.attr("data-img")&&(c.prepend('<div class="preview"><img src="'+c.attr("data-img")+
'"/></div>'),c.children(".preview").children("img").width(f),c.children(".preview").children("img").height(g));"image"!=b.type&&(c.find(".info"),c.find(".infoText"),i=c.find(".playcontrols"),i.append('<div class="playSimple"></div>'),i.append('<div class="playHover"></div>'),i.append('<div class="stopSimple"></div>'),i.append('<div class="stopHover"></div>'),i.hover(function(){i.children().eq(1).animate({opacity:1},{queue:false,duration:300});i.children().eq(3).animate({opacity:1},{queue:false,duration:300})},
function(){i.children().eq(1).animate({opacity:0},{queue:false,duration:300});i.children().eq(3).animate({opacity:0},{queue:false,duration:300})}),scrubbar=c.find(".scrubbar"),scrubbar.append('<div class="scrub-bg"></div>'),scrubbar.append('<div class="scrub-buffer"></div>'),scrubbar.append('<div class="scrub"></div>'),j=c.find(".volumecontrols"),j.append('<div class="volumeicon"></div>'),j.append('<div class="volume_static"></div>'),j.append('<div class="volume_active"></div>'),j.append('<div class="volume_cut"></div>'),
p=c.find(".fscreencontrols"),p.append('<div class="full"></div>'),p.append('<div class="fullHover"></div>'),p.hover(function(){p.children().eq(1).animate({opacity:1},{queue:false,duration:300})},function(){p.children().eq(1).animate({opacity:0},{queue:false,duration:300})}),0<a.find(".videoDescription").length&&(J=a.find(".videoDescription").html(),a.find(".videoDescription").remove()),"on"!=b.cueVideo?0==c.css("opacity")&&(c.animate({opacity:1},1E3),s(f,g),c.bind("click",K)):K(),h(window).bind("resize",
F),F())}})();h.fn.vPlayer.checkState=function(){"youtube"==b.type&&(d.getPlayerState&&0==d.getPlayerState())&&P()}})}})(jQuery);function onYouTubePlayerReady(h){ytplayer=document.getElementById(h);ytplayer.addEventListener("onStateChange","onytplayerStateChange");h=h.substr(8);ytplayer.loadVideoById(h);ytplayer.pauseVideo()}function onytplayerStateChange(h){0==h&&jQuery(".vplayer").vPlayer.checkState()}
function is_ios(){return-1!=navigator.platform.indexOf("iPhone")||-1!=navigator.platform.indexOf("iPod")||-1!=navigator.platform.indexOf("iPad")}function is_ie9(){return $.browser.msie&&9==parseInt($.browser.version)?!0:!1}function is_ie8(){return $.browser.msie&&9>parseInt($.browser.version)?!0:!1};